cbee: cbee Namespace Reference
cbee Namespace Reference
Classes
class EPoller
class Event
class EventModifierInterface
class EventTimerFd
class EventTrigger
class EventTriggerFd
class InetAddress
struct Initializer
class Logger
class Server
class ServerInterface
class Sockaddr
class SocketFd
class TimerHandler
class Timestamp
Typedefs
typedef std::function< void()> ConnectedFunc
typedef std::function< void()> ReadDoneFunc
typedef std::function< void()> WriteDoneFunc
typedef std::function< void()> DisConnectedFunc
typedef Event * EventHandler
Functions
bool operator< (Timestamp lhs, Timestamp rhs)
bool operator== (Timestamp lhs, Timestamp rhs)
bool operator> (Timestamp lhs, Timestamp rhs)
bool operator!= (Timestamp lhs, Timestamp rhs)
Variables
static Initializer i
static const int kInitialActiveEventsSize = 16
Typedef Documentation
ConnectedFunc
typedef std::function<void()> cbee::ConnectedFunc
DisConnectedFunc
typedef std::function<void()> cbee::DisConnectedFunc
EventHandler
typedef Event* cbee::EventHandler
ReadDoneFunc
typedef std::function<void()> cbee::ReadDoneFunc
WriteDoneFunc
typedef std::function<void()> cbee::WriteDoneFunc
Function Documentation
operator!=()
bool cbee::operator!= (Timestamp lhs, Timestamp rhs) inline
References cbee::Timestamp::getMicroSeconds().
operator<()
bool cbee::operator< (Timestamp lhs, Timestamp rhs) inline
References cbee::Timestamp::getMicroSeconds().
operator==()
bool cbee::operator== (Timestamp lhs, Timestamp rhs) inline
References cbee::Timestamp::getMicroSeconds().
Referenced by el::base::LogFormat::~LogFormat().
operator>()
bool cbee::operator> (Timestamp lhs, Timestamp rhs) inline
References cbee::Timestamp::getMicroSeconds().
Variable Documentation
i
Initializer cbee::i static
Referenced by el::base::Writer::construct(), el::base::utils::DateTime::formatTime(), el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator!=(), el::base::utils::operator<<(), el::base::utils::AbstractRegistry< T_Ptr, std::vector< T_Ptr *> >::operator==(), cbee::EPoller::poll(), el::base::Writer::processDispatch(), el::base::utils::CommandLineArgs::setArgs(), and el::base::MessageBuilder::writeIterator().
kInitialActiveEventsSize
const int cbee::kInitialActiveEventsSize = 16 static