cbee: cbee::EventTrigger Class Reference
cbee::EventTrigger Class Reference
#include "EventTrigger.h"
Public Member Functions
EventTrigger (const EventModifierInterface &modifier)
~EventTrigger ()
void triggerOnce () const
Private Member Functions
EventTrigger (const EventTrigger &)=delete
EventTrigger & operator= (const EventTrigger &)=delete
void handleRead () const
Private Attributes
const EventModifierInterface & eventModifier
const EventTriggerFd fd
Event event
Constructor & Destructor Documentation
EventTrigger() [1/2]
cbee::EventTrigger::EventTrigger (const EventModifierInterface & modifier)
References event, eventModifier, fd, cbee::EventTriggerFd::getFd(), handleRead(), and cbee::EventModifierInterface::updateEvent().
~EventTrigger()
cbee::EventTrigger::~EventTrigger ()
References cbee::EventModifierInterface::deleteEvent(), eventModifier, fd, and cbee::EventTriggerFd::getFd().
EventTrigger() [2/2]
cbee::EventTrigger::EventTrigger (const EventTrigger &) private delete
Member Function Documentation
handleRead()
void cbee::EventTrigger::handleRead () const private
References cbee::EventTriggerFd::cleanEvents(), and fd.
Referenced by EventTrigger().
operator=()
EventTrigger& cbee::EventTrigger::operator= (const EventTrigger &) private delete
triggerOnce()
void cbee::EventTrigger::triggerOnce () const
References fd, and cbee::EventTriggerFd::triggerEvent().
Referenced by cbee::IoManager::quit(), and cbee::IoManager::runInLoopThread().
Member Data Documentation
event
Event cbee::EventTrigger::event private
Referenced by EventTrigger().
eventModifier
const EventModifierInterface& cbee::EventTrigger::eventModifier private
Referenced by EventTrigger(), and ~EventTrigger().
fd
const EventTriggerFd cbee::EventTrigger::fd private
Referenced by EventTrigger(), handleRead(), triggerOnce(), and ~EventTrigger().
The documentation for this class was generated from the following files:
src/internal/EventTrigger.h
src/internal/EventTrigger.cpp