cbee: cbee::TimerHandler Class Reference
cbee::TimerHandler Class Reference
#include "TimerHandler.h"
Public Types
typedef std::function< void()> TimerFunc
Public Member Functions
TimerHandler (Timestamp time, double interval, TimerFunc cb)
void run () const
bool updateExpiredTime (Timestamp handleTime)
Timestamp getExpiredTime () const
int getId () const
Private Attributes
Timestamp expiredTime
const double intervalSeconds
const TimerFunc callback
const int id
Static Private Attributes
static std::atomic< int > s_numberOfCreated = 0
Member Typedef Documentation
TimerFunc
typedef std::function<void()> cbee::TimerHandler::TimerFunc
Constructor & Destructor Documentation
TimerHandler()
cbee::TimerHandler::TimerHandler (Timestamp time, double interval, TimerFunc cb)
Member Function Documentation
getExpiredTime()
Timestamp cbee::TimerHandler::getExpiredTime () const
References expiredTime.
Referenced by cbee::EventTimerHandlerQueue::addHandler().
getId()
int cbee::TimerHandler::getId () const
References id.
Referenced by cbee::IoManager::runAfter(), and cbee::IoManager::runEvery().
run()
void cbee::TimerHandler::run () const
References callback.
updateExpiredTime()
bool cbee::TimerHandler::updateExpiredTime (Timestamp handleTime)
References cbee::Timestamp::addSeconds(), expiredTime, and intervalSeconds.
Member Data Documentation
callback
const TimerFunc cbee::TimerHandler::callback private
Referenced by run().
expiredTime
Timestamp cbee::TimerHandler::expiredTime private
Referenced by getExpiredTime(), and updateExpiredTime().
id
const int cbee::TimerHandler::id private
Referenced by getId().
intervalSeconds
const double cbee::TimerHandler::intervalSeconds private
Referenced by updateExpiredTime().
s_numberOfCreated
std::atomic< int > cbee::TimerHandler::s_numberOfCreated = 0 static private
The documentation for this class was generated from the following files:
src/internal/TimerHandler.h
src/internal/TimerHandler.cpp