cbee: el::base::TypedConfigurations Class Reference
el::base::TypedConfigurations Class Reference
Configurations with data types.
#include "easylogging++.h"
Public Member Functions
TypedConfigurations (Configurations *configurations, base::LogStreamsReferenceMap *logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
TypedConfigurations (const TypedConfigurations &other)
virtual ~TypedConfigurations (void)
const Configurations * configurations (void) const
bool enabled (Level level)
bool toFile (Level level)
const std::string & filename (Level level)
bool toStandardOutput (Level level)
const base::LogFormat & logFormat (Level level)
const base::SubsecondPrecision & subsecondPrecision (Level level=Level::Global)
const base::MillisecondsWidth & millisecondsWidth (Level level=Level::Global)
bool performanceTracking (Level level=Level::Global)
base::type::fstream_t * fileStream (Level level)
std::size_t maxLogFileSize (Level level)
std::size_t logFlushThreshold (Level level)
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
template<typename Conf_T >
Conf_T getConfigByVal (Level level, const std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & getConfigByRef (Level level, std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T unsafeGetConfigByVal (Level level, const std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
Conf_T & unsafeGetConfigByRef (Level level, std::unordered_map< Level, Conf_T > *confMap, const char *confName)
template<typename Conf_T >
void setValue (Level level, const Conf_T &value, std::unordered_map< Level, Conf_T > *confMap, bool includeGlobalLevel=true)
void build (Configurations *configurations)
unsigned long getULong (std::string confVal)
std::string resolveFilename (const std::string &filename)
void insertFile (Level level, const std::string &fullFilename)
bool unsafeValidateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
bool validateFileRolling (Level level, const PreRollOutCallback &preRollOutCallback)
Private Attributes
Configurations * m_configurations
std::unordered_map< Level, bool > m_enabledMap
std::unordered_map< Level, bool > m_toFileMap
std::unordered_map< Level, std::string > m_filenameMap
std::unordered_map< Level, bool > m_toStandardOutputMap
std::unordered_map< Level, base::LogFormat > m_logFormatMap
std::unordered_map< Level, base::SubsecondPrecision > m_subsecondPrecisionMap
std::unordered_map< Level, bool > m_performanceTrackingMap
std::unordered_map< Level, base::FileStreamPtr > m_fileStreamMap
std::unordered_map< Level, std::size_t > m_maxLogFileSizeMap
std::unordered_map< Level, std::size_t > m_logFlushThresholdMap
base::LogStreamsReferenceMap * m_logStreamsReference
Friends
class el::Helpers
class el::base::MessageBuilder
class el::base::Writer
class el::base::DefaultLogDispatchCallback
class el::base::LogDispatcher
Additional Inherited Members
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Configurations with data types.
el::Configurations have string based values. This is whats used internally in order to read correct configurations. This is to perform faster while writing logs using correct configurations.
This is thread safe and final class containing non-virtual destructor (means nothing should inherit this class)
Constructor & Destructor Documentation
TypedConfigurations() [1/2]
el::base::TypedConfigurations::TypedConfigurations (Configurations * configurations, base::LogStreamsReferenceMap * logStreamsReference)
Constructor to initialize (construct) the object off el::Configurations.
Parameters
configurations Configurations pointer/reference to base this typed configurations off.
logStreamsReference Use ELPP->registeredLoggers()->logStreamsReference()
TypedConfigurations() [2/2]
el::base::TypedConfigurations::TypedConfigurations (const TypedConfigurations & other)
References m_configurations, and m_logStreamsReference.
~TypedConfigurations()
virtual el::base::TypedConfigurations::~TypedConfigurations (void) inline virtual
Member Function Documentation
build()
void el::base::TypedConfigurations::build (Configurations * configurations) private
References el::base::utils::AbstractRegistry< T_Ptr, Container >::begin(), el::Configuration::configurationType(), el::base::defaultPreRollOutCallback(), el::Enabled, el::base::utils::AbstractRegistry< T_Ptr, Container >::end(), el::Filename, el::Format, el::Global, el::Configuration::level(), el::LogFlushThreshold, el::MaxLogFileSize, el::PerformanceTracking, el::SubsecondPrecision, el::ToFile, el::ToStandardOutput, el::base::utils::Str::trim(), and el::Configuration::value().
configurations()
const Configurations* el::base::TypedConfigurations::configurations (void) const inline
References el::Global.
Referenced by el::Logger::configure().
enabled()
bool el::base::TypedConfigurations::enabled (Level level)
References el::base::LogFormat::level().
filename()
const std::string & el::base::TypedConfigurations::filename (Level level)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), el::LogDispatchCallback::fileHandle(), and el::LogDispatchCallback::handle().
fileStream()
base::type::fstream_t * el::base::TypedConfigurations::fileStream (Level level)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), and el::Logger::flush().
getConfigByRef()
template<typename Conf_T > Conf_T& el::base::TypedConfigurations::getConfigByRef (Level level, std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
getConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::getConfigByVal (Level level, const std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
getULong()
unsigned long el::base::TypedConfigurations::getULong (std::string confVal) private
References ELPP_ASSERT, el::base::utils::Str::isDigit(), and el::base::utils::Str::trim().
insertFile()
void el::base::TypedConfigurations::insertFile (Level level, const std::string & fullFilename) private
References el::LevelHelper::convertToString(), el::base::utils::File::createPath(), ELPP_INTERNAL_ERROR, el::base::utils::File::extractPathFromFilename(), el::Global, el::base::consts::kFilePathSeperator, el::base::LogFormat::level(), and el::base::utils::File::newFileStream().
logFlushThreshold()
std::size_t el::base::TypedConfigurations::logFlushThreshold (Level level)
References el::base::LogFormat::level().
logFormat()
const base::LogFormat & el::base::TypedConfigurations::logFormat (Level level)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogBuilder::build(), and el::Logger::resolveLoggerFormatSpec().
maxLogFileSize()
std::size_t el::base::TypedConfigurations::maxLogFileSize (Level level)
References el::base::LogFormat::level().
millisecondsWidth()
const base::MillisecondsWidth & el::base::TypedConfigurations::millisecondsWidth (Level level = Level::Global)
References el::base::LogFormat::level().
performanceTracking()
bool el::base::TypedConfigurations::performanceTracking (Level level = Level::Global)
References el::base::LogFormat::level().
Referenced by el::base::PErrorWriter::~PErrorWriter().
resolveFilename()
std::string el::base::TypedConfigurations::resolveFilename (const std::string & filename) private
References el::base::utils::DateTime::getDateTime(), el::base::consts::kDateTimeFormatSpecifierForFilename, el::base::consts::kDefaultDateTimeFormatInFilename, el::base::consts::kFormatSpecifierChar, and el::base::utils::Str::replaceAll().
setValue()
template<typename Conf_T > void el::base::TypedConfigurations::setValue (Level level, const Conf_T & value, std::unordered_map< Level, Conf_T > * confMap, bool includeGlobalLevel = true) inline private
References el::Global, and el::base::consts::value.
subsecondPrecision()
const base::SubsecondPrecision & el::base::TypedConfigurations::subsecondPrecision (Level level = Level::Global)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogBuilder::build().
toFile()
bool el::base::TypedConfigurations::toFile (Level level)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch(), and el::Logger::flush().
toStandardOutput()
bool el::base::TypedConfigurations::toStandardOutput (Level level)
References el::base::LogFormat::level().
Referenced by el::base::DefaultLogDispatchCallback::dispatch().
unsafeGetConfigByRef()
template<typename Conf_T > Conf_T& el::base::TypedConfigurations::unsafeGetConfigByRef (Level level, std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
References el::LevelHelper::convertToString(), ELPP_INTERNAL_ERROR, ELPP_UNUSED, and el::Global.
unsafeGetConfigByVal()
template<typename Conf_T > Conf_T el::base::TypedConfigurations::unsafeGetConfigByVal (Level level, const std::unordered_map< Level, Conf_T > * confMap, const char * confName) inline private
References el::LevelHelper::convertToString(), ELPP_INTERNAL_ERROR, ELPP_UNUSED, and el::Global.
unsafeValidateFileRolling()
bool el::base::TypedConfigurations::unsafeValidateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) private
References el::LevelHelper::convertToString(), ELPP_INTERNAL_INFO, and el::base::utils::File::getSizeOfFile().
validateFileRolling()
bool el::base::TypedConfigurations::validateFileRolling (Level level, const PreRollOutCallback & preRollOutCallback) inline private
Referenced by el::base::LogDispatcher::dispatch(), and el::Helpers::validateFileRolling().
Friends And Related Function Documentation
el::base::DefaultLogDispatchCallback
friend class el::base::DefaultLogDispatchCallback friend
el::base::LogDispatcher
friend class el::base::LogDispatcher friend
el::base::MessageBuilder
friend class el::base::MessageBuilder friend
el::base::Writer
friend class el::base::Writer friend
el::Helpers
friend class el::Helpers friend
Member Data Documentation
m_configurations
Configurations* el::base::TypedConfigurations::m_configurations private
Referenced by TypedConfigurations().
m_enabledMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_enabledMap private
m_filenameMap
std::unordered_map<Level, std::string> el::base::TypedConfigurations::m_filenameMap private
m_fileStreamMap
std::unordered_map<Level, base::FileStreamPtr> el::base::TypedConfigurations::m_fileStreamMap private
m_logFlushThresholdMap
std::unordered_map<Level, std::size_t> el::base::TypedConfigurations::m_logFlushThresholdMap private
m_logFormatMap
std::unordered_map<Level, base::LogFormat> el::base::TypedConfigurations::m_logFormatMap private
m_logStreamsReference
base::LogStreamsReferenceMap* el::base::TypedConfigurations::m_logStreamsReference private
Referenced by TypedConfigurations().
m_maxLogFileSizeMap
std::unordered_map<Level, std::size_t> el::base::TypedConfigurations::m_maxLogFileSizeMap private
m_performanceTrackingMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_performanceTrackingMap private
m_subsecondPrecisionMap
std::unordered_map<Level, base::SubsecondPrecision> el::base::TypedConfigurations::m_subsecondPrecisionMap private
m_toFileMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_toFileMap private
m_toStandardOutputMap
std::unordered_map<Level, bool> el::base::TypedConfigurations::m_toStandardOutputMap private
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp