cbee: cbee::Socket Class Reference
cbee::Socket Class Reference
#include "Socket.h"
Public Member Functions
Socket ()
Socket (int socketFd)
~Socket ()
void shutdownRead ()
void shutdownWrite ()
void shutdown ()
void setNonBlock ()
void bind (const Sockaddr &serverAddr)
void listen ()
int accept (Sockaddr *connectAddr)
void connect (const Sockaddr &serverAddr)
int getFd () const
int read (void *buf, int count)
int write (const void *buf, int count)
Private Member Functions
Socket (const Socket &)=delete
Socket & operator= (const Socket &)=delete
struct sockaddr * sockaddrCast (Sockaddr *addr)
const struct sockaddr * sockaddrCast (const Sockaddr *addr)
Private Attributes
const int fd
Constructor & Destructor Documentation
Socket() [1/3]
cbee::Socket::Socket ()
References fd.
Socket() [2/3]
cbee::Socket::Socket (int socketFd) explicit
References fd.
~Socket()
cbee::Socket::~Socket ()
References fd.
Socket() [3/3]
cbee::Socket::Socket (const Socket &) private delete
Member Function Documentation
accept()
int cbee::Socket::accept (Sockaddr * connectAddr)
References fd, and sockaddrCast().
bind()
void cbee::Socket::bind (const Sockaddr & serverAddr)
References fd, and sockaddrCast().
connect()
void cbee::Socket::connect (const Sockaddr & serverAddr)
References fd, and sockaddrCast().
getFd()
int cbee::Socket::getFd () const
References fd.
Referenced by cbee::EPoller::deleteEvent(), cbee::Event::handleEvent(), and cbee::EPoller::updateEvent().
listen()
void cbee::Socket::listen ()
References fd.
operator=()
Socket& cbee::Socket::operator= (const Socket &) private delete
read()
int cbee::Socket::read (void * buf, int count)
References fd.
setNonBlock()
void cbee::Socket::setNonBlock ()
References fd.
shutdown()
void cbee::Socket::shutdown ()
References fd.
Referenced by shutdownRead(), and shutdownWrite().
shutdownRead()
void cbee::Socket::shutdownRead ()
References fd, and shutdown().
shutdownWrite()
void cbee::Socket::shutdownWrite ()
References fd, and shutdown().
sockaddrCast() [1/2]
struct sockaddr * cbee::Socket::sockaddrCast (Sockaddr * addr) private
Referenced by accept(), bind(), and connect().
sockaddrCast() [2/2]
const struct sockaddr * cbee::Socket::sockaddrCast (const Sockaddr * addr) private
write()
int cbee::Socket::write (const void * buf, int count)
References fd.
Member Data Documentation
fd
const int cbee::Socket::fd private
Referenced by accept(), bind(), connect(), getFd(), listen(), read(), setNonBlock(), shutdown(), shutdownRead(), shutdownWrite(), Socket(), write(), and ~Socket().
The documentation for this class was generated from the following files:
src/internal/system/Socket.h
src/internal/system/Socket.cpp