cbee: el::base::LogDispatcher Class Reference
el::base::LogDispatcher Class Reference
Dispatches log messages.
#include "easylogging++.h"
Public Member Functions
LogDispatcher (bool proceed, LogMessage *logMessage, base::DispatchAction dispatchAction)
void dispatch (void)
Private Attributes
bool m_proceed
LogMessage * m_logMessage
base::DispatchAction m_dispatchAction
Additional Inherited Members
Private Member Functions inherited from el::base::NoCopy
NoCopy (void)
Detailed Description
Dispatches log messages.
Constructor & Destructor Documentation
LogDispatcher()
el::base::LogDispatcher::LogDispatcher (bool proceed, LogMessage * logMessage, base::DispatchAction dispatchAction) inline
Member Function Documentation
dispatch()
void el::base::LogDispatcher::dispatch (void)
References ELPP, el::Callback< T >::enabled(), el::LogDispatchCallback::handle(), el::base::None, el::LogDispatchData::setDispatchAction(), el::LogDispatchData::setLogMessage(), el::StrictLogFileSizeCheck, and el::base::TypedConfigurations::validateFileRolling().
Referenced by el::base::Writer::triggerDispatch().
Member Data Documentation
m_dispatchAction
base::DispatchAction el::base::LogDispatcher::m_dispatchAction private
m_logMessage
LogMessage* el::base::LogDispatcher::m_logMessage private
m_proceed
bool el::base::LogDispatcher::m_proceed private
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp