cbee: el::base::PErrorWriter Class Reference
el::base::PErrorWriter Class Reference
#include "easylogging++.h"
Public Member Functions
PErrorWriter (Level level, const char *file, base::type::LineNumber line, const char *func, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel=0)
virtual ~PErrorWriter (void)
Public Member Functions inherited from el::base::Writer
Writer (Level level, const char *file, base::type::LineNumber line, const char *func, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel=0)
Writer (LogMessage *msg, base::DispatchAction dispatchAction=base::DispatchAction::NormalLog)
virtual ~Writer (void)
template<typename T >
Writer & operator<< (const T &log)
Writer & operator<< (std::ostream &(*log)(std::ostream &))
operator bool ()
Writer & construct (Logger *logger, bool needLock=true)
Writer & construct (int count, const char *loggerIds,...)
Additional Inherited Members
Protected Member Functions inherited from el::base::Writer
void initializeLogger (const std::string &loggerId, bool lookup=true, bool needLock=true)
void processDispatch ()
void triggerDispatch (void)
Protected Attributes inherited from el::base::Writer
LogMessage * m_msg
Level m_level
const char * m_file
const base::type::LineNumber m_line
const char * m_func
base::type::VerboseLevel m_verboseLevel
Logger * m_logger
bool m_proceed
base::MessageBuilder m_messageBuilder
base::DispatchAction m_dispatchAction
std::vector< std::string > m_loggerIds
Constructor & Destructor Documentation
PErrorWriter()
el::base::PErrorWriter::PErrorWriter (Level level, const char * file, base::type::LineNumber line, const char * func, base::DispatchAction dispatchAction = base::DispatchAction::NormalLog, base::type::VerboseLevel verboseLevel = 0) inline
References el::base::Writer::construct(), el::Debug, ELPP, ELPP_INTERNAL_ERROR, ELPP_LITERAL, el::Error, el::Fatal, el::Info, el::base::MessageBuilder::initialize(), el::base::consts::kFormatSpecifierChar, el::base::consts::kFormatSpecifierCharValue, el::Logger::log(), el::base::NormalLog, el::Trace, el::base::consts::value, el::Verbose, and el::Warning.
~PErrorWriter()
el::base::PErrorWriter::~PErrorWriter (void) virtual
References ELPP, ELPP_LITERAL, ELPP_UNUSED, el::Callback< T >::enabled(), el::FixedTimeFormat, el::base::utils::DateTime::formatTime(), el::base::utils::DateTime::getTimeDifference(), el::base::utils::DateTime::gettimeofday(), el::Callback< T >::handle(), el::base::consts::kTimeFormats, el::base::VRegistry::level(), el::base::threading::ThreadSafe::lock(), el::base::VRegistry::m_level, el::Logger::m_typedConfigurations, el::base::TypedConfigurations::performanceTracking(), and el::base::consts::unit.
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp