cbee: el::base::RegisteredLoggers Class Reference
el::base::RegisteredLoggers Class Reference
Loggers repository.
#include "easylogging++.h"
Public Member Functions
RegisteredLoggers (const LogBuilderPtr &defaultLogBuilder)
virtual ~RegisteredLoggers (void)
void setDefaultConfigurations (const Configurations &configurations)
Configurations * defaultConfigurations (void)
Logger * get (const std::string &id, bool forceCreation=true)
template<typename T >
bool installLoggerRegistrationCallback (const std::string &id)
template<typename T >
void uninstallLoggerRegistrationCallback (const std::string &id)
template<typename T >
T * loggerRegistrationCallback (const std::string &id)
bool remove (const std::string &id)
bool has (const std::string &id)
void unregister (Logger *&logger)
base::LogStreamsReferenceMap * logStreamsReference (void)
void flushAll (void)
void setDefaultLogBuilder (LogBuilderPtr &logBuilderPtr)
Public Member Functions inherited from el::base::utils::Registry< Logger, std::string >
Registry (void)
Registry (const Registry &sr)
Copy constructor that is useful for base classes. Try to avoid this constructor, use move constructor.
Registry & operator= (const Registry &sr)
Assignment operator that unregisters all the existing registeries and deeply copies each of repo element.
virtual ~Registry (void)
Public Member Functions inherited from el::base::utils::AbstractRegistry< Logger, std::unordered_map< std::string, Logger *> >
AbstractRegistry (void)
Default constructor.
AbstractRegistry (AbstractRegistry &&sr)
Move constructor that is useful for base classes.
bool operator== (const AbstractRegistry< Logger, std::unordered_map< std::string, Logger * > > &other)
bool operator!= (const AbstractRegistry< Logger, std::unordered_map< std::string, Logger * > > &other)
AbstractRegistry & operator= (AbstractRegistry &&sr)
Assignment move operator.
virtual ~AbstractRegistry (void)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual std::unordered_map< std::string, Logger * > & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const std::unordered_map< std::string, Logger * > & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
void unsafeFlushAll (void)
Private Attributes
LogBuilderPtr m_defaultLogBuilder
Configurations m_defaultConfigurations
base::LogStreamsReferenceMap m_logStreamsReference
std::unordered_map< std::string, base::type::LoggerRegistrationCallbackPtr > m_loggerRegistrationCallbacks
Friends
class el::base::Storage
Additional Inherited Members
Public Types inherited from el::base::utils::Registry< Logger, std::string >
typedef Registry< Logger, std::string >::iterator iterator
typedef Registry< Logger, std::string >::const_iterator const_iterator
Public Types inherited from el::base::utils::AbstractRegistry< Logger, std::unordered_map< std::string, Logger *> >
typedef std::unordered_map< std::string, Logger * > ::iterator iterator
typedef std::unordered_map< std::string, Logger * > ::const_iterator const_iterator
Protected Member Functions inherited from el::base::utils::Registry< Logger, std::string >
virtual void unregisterAll (void) ELPP_FINAL
Unregisters all the pointers from current repository.
virtual void registerNew (const std::string &uniqKey, Logger *ptr) ELPP_FINAL
Registers new registry to repository.
void unregister (const std::string &uniqKey)
Unregisters single entry mapped to specified unique key.
Logger * get (const std::string &uniqKey)
Gets pointer from repository. If none found, nullptr is returned.
Protected Member Functions inherited from el::base::utils::AbstractRegistry< Logger, std::unordered_map< std::string, Logger *> >
virtual void deepCopy (const AbstractRegistry< Logger, std::unordered_map< std::string, Logger * > > &)=0
void reinitDeepCopy (const AbstractRegistry< Logger, std::unordered_map< std::string, Logger * > > &sr)
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Detailed Description
Loggers repository.
Constructor & Destructor Documentation
RegisteredLoggers()
el::base::RegisteredLoggers::RegisteredLoggers (const LogBuilderPtr & defaultLogBuilder) explicit
References m_defaultConfigurations, and el::Configurations::setToDefault().
~RegisteredLoggers()
virtual el::base::RegisteredLoggers::~RegisteredLoggers (void) inline virtual
Member Function Documentation
defaultConfigurations()
Configurations* el::base::RegisteredLoggers::defaultConfigurations (void) inline
flushAll()
void el::base::RegisteredLoggers::flushAll (void) inline
get()
Logger * el::base::RegisteredLoggers::get (const std::string & id, bool forceCreation = true)
References ELPP_ASSERT, el::Callback< T >::enabled(), el::base::utils::Registry< T_Ptr, T_Key >::get(), el::Callback< T >::handle(), el::Logger::isValidId(), el::base::threading::ThreadSafe::lock(), m_defaultConfigurations, m_defaultLogBuilder, el::Logger::m_logBuilder, m_loggerRegistrationCallbacks, m_logStreamsReference, and el::base::utils::Registry< Logger, std::string >::registerNew().
has()
bool el::base::RegisteredLoggers::has (const std::string & id) inline
installLoggerRegistrationCallback()
template<typename T > bool el::base::RegisteredLoggers::installLoggerRegistrationCallback (const std::string & id) inline
loggerRegistrationCallback()
template<typename T > T* el::base::RegisteredLoggers::loggerRegistrationCallback (const std::string & id) inline
logStreamsReference()
base::LogStreamsReferenceMap* el::base::RegisteredLoggers::logStreamsReference (void) inline
remove()
bool el::base::RegisteredLoggers::remove (const std::string & id)
References el::base::utils::Registry< T_Ptr, T_Key >::get(), el::base::consts::kDefaultLoggerId, and unregister().
setDefaultConfigurations()
void el::base::RegisteredLoggers::setDefaultConfigurations (const Configurations & configurations) inline
setDefaultLogBuilder()
void el::base::RegisteredLoggers::setDefaultLogBuilder (LogBuilderPtr & logBuilderPtr) inline
uninstallLoggerRegistrationCallback()
template<typename T > void el::base::RegisteredLoggers::uninstallLoggerRegistrationCallback (const std::string & id) inline
unregister()
void el::base::RegisteredLoggers::unregister (Logger *& logger) inline
References el::Logger::id(), and el::base::utils::Registry< T_Ptr, T_Key >::unregister().
Referenced by remove().
unsafeFlushAll()
void el::base::RegisteredLoggers::unsafeFlushAll (void) private
References ELPP_INTERNAL_INFO, and m_logStreamsReference.
Friends And Related Function Documentation
el::base::Storage
friend class el::base::Storage friend
Member Data Documentation
m_defaultConfigurations
Configurations el::base::RegisteredLoggers::m_defaultConfigurations private
Referenced by get(), and RegisteredLoggers().
m_defaultLogBuilder
LogBuilderPtr el::base::RegisteredLoggers::m_defaultLogBuilder private
Referenced by get().
m_loggerRegistrationCallbacks
std::unordered_map<std::string, base::type::LoggerRegistrationCallbackPtr> el::base::RegisteredLoggers::m_loggerRegistrationCallbacks private
Referenced by get().
m_logStreamsReference
base::LogStreamsReferenceMap el::base::RegisteredLoggers::m_logStreamsReference private
Referenced by get(), and unsafeFlushAll().
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp