cbee: cbee::EventTimerHandlerQueue Class Reference
cbee::EventTimerHandlerQueue Class Reference
#include "EventTimerHandlerQueue.h"
Public Member Functions
EventTimerHandlerQueue (const EventModifierInterface &modifier)
~EventTimerHandlerQueue ()
void addHandler (const TimerHandler &handler)
void cancelHandler (int id)
Private Member Functions
EventTimerHandlerQueue (const EventTimerHandlerQueue &)=delete
EventTimerHandlerQueue & operator= (const EventTimerHandlerQueue &)=delete
void handleRead ()
std::vector< TimerHandler > extractExpiredHandlers (Timestamp handleTime)
void triggerEvent (const std::vector< TimerHandler > &expiredHandlers, Timestamp handleTime)
Private Attributes
const EventModifierInterface & eventModifier
const EventTimerFd fd
Event event
std::multimap< Timestamp, TimerHandler > handlerQueue
Constructor & Destructor Documentation
EventTimerHandlerQueue() [1/2]
cbee::EventTimerHandlerQueue::EventTimerHandlerQueue (const EventModifierInterface & modifier)
References event, eventModifier, fd, cbee::EventTimerFd::getFd(), handleRead(), and cbee::EventModifierInterface::updateEvent().
~EventTimerHandlerQueue()
cbee::EventTimerHandlerQueue::~EventTimerHandlerQueue ()
References cbee::EventModifierInterface::deleteEvent(), eventModifier, fd, and cbee::EventTimerFd::getFd().
EventTimerHandlerQueue() [2/2]
cbee::EventTimerHandlerQueue::EventTimerHandlerQueue (const EventTimerHandlerQueue &) private delete
Member Function Documentation
addHandler()
void cbee::EventTimerHandlerQueue::addHandler (const TimerHandler & handler)
References fd, cbee::TimerHandler::getExpiredTime(), handlerQueue, and cbee::EventTimerFd::triggerEventAt().
Referenced by cbee::IoManager::runAfter(), and cbee::IoManager::runEvery().
cancelHandler()
void cbee::EventTimerHandlerQueue::cancelHandler (int id)
References handlerQueue.
Referenced by cbee::IoManager::cancelTimerHandler().
extractExpiredHandlers()
std::vector< TimerHandler > cbee::EventTimerHandlerQueue::extractExpiredHandlers (Timestamp handleTime) private
References handlerQueue, and triggerEvent().
Referenced by handleRead().
handleRead()
void cbee::EventTimerHandlerQueue::handleRead () private
References cbee::EventTimerFd::cleanEvent(), extractExpiredHandlers(), fd, cbee::Timestamp::now(), and triggerEvent().
Referenced by EventTimerHandlerQueue().
operator=()
EventTimerHandlerQueue& cbee::EventTimerHandlerQueue::operator= (const EventTimerHandlerQueue &) private delete
triggerEvent()
void cbee::EventTimerHandlerQueue::triggerEvent (const std::vector< TimerHandler > & expiredHandlers, Timestamp handleTime) private
References fd, handlerQueue, and cbee::EventTimerFd::triggerEventAt().
Referenced by extractExpiredHandlers(), and handleRead().
Member Data Documentation
event
Event cbee::EventTimerHandlerQueue::event private
Referenced by EventTimerHandlerQueue().
eventModifier
const EventModifierInterface& cbee::EventTimerHandlerQueue::eventModifier private
Referenced by EventTimerHandlerQueue(), and ~EventTimerHandlerQueue().
fd
const EventTimerFd cbee::EventTimerHandlerQueue::fd private
Referenced by addHandler(), EventTimerHandlerQueue(), handleRead(), triggerEvent(), and ~EventTimerHandlerQueue().
handlerQueue
std::multimap<Timestamp, TimerHandler> cbee::EventTimerHandlerQueue::handlerQueue private
Referenced by addHandler(), cancelHandler(), extractExpiredHandlers(), and triggerEvent().
The documentation for this class was generated from the following files:
src/internal/EventTimerHandlerQueue.h
src/internal/EventTimerHandlerQueue.cpp