cbee: el::base::threading::ThreadSafe Class Reference
el::base::threading::ThreadSafe Class Reference
Base of thread safe class, this class is inheritable-only.
#include "easylogging++.h"
Public Member Functions
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
ThreadSafe (void)
virtual ~ThreadSafe (void)
Private Attributes
base::threading::Mutex m_mutex
Detailed Description
Base of thread safe class, this class is inheritable-only.
Constructor & Destructor Documentation
ThreadSafe()
el::base::threading::ThreadSafe::ThreadSafe (void) inline protected
~ThreadSafe()
virtual el::base::threading::ThreadSafe::~ThreadSafe (void) inline protected virtual
Member Function Documentation
acquireLock()
virtual void el::base::threading::ThreadSafe::acquireLock (void) inline virtual
Referenced by el::Helpers::logDispatchCallback().
lock()
virtual base::threading::Mutex& el::base::threading::ThreadSafe::lock (void) inline virtual
Referenced by el::base::VRegistry::allowed(), el::Logger::configure(), el::Logger::flush(), el::base::RegisteredLoggers::get(), el::LogDispatchCallback::handle(), el::Configurations::hasConfiguration(), el::Configurations::set(), el::Configurations::setFromBase(), el::base::VRegistry::setLevel(), el::base::VRegistry::setModules(), el::Configurations::setRemainingToDefault(), and el::base::PErrorWriter::~PErrorWriter().
releaseLock()
virtual void el::base::threading::ThreadSafe::releaseLock (void) inline virtual
Referenced by el::Helpers::logDispatchCallback().
Member Data Documentation
m_mutex
base::threading::Mutex el::base::threading::ThreadSafe::m_mutex private
The documentation for this class was generated from the following file:
src/internal/lib/easylogging++.h