cbee: cbee::InetAddress Class Reference
cbee::InetAddress Class Reference
#include "InetAddress.h"
Public Member Functions
InetAddress (uint16_t port, bool loopbackOnly=false)
InetAddress (const char *ip, uint16_t port)
std::string getIp () const
std::string getIpPort () const
Private Member Functions
InetAddress (const InetAddress &)=delete
InetAddress & operator= (const InetAddress &)=delete
Private Attributes
Sockaddr address
Constructor & Destructor Documentation
InetAddress() [1/3]
cbee::InetAddress::InetAddress (uint16_t port, bool loopbackOnly = false)
References address, cbee::Sockaddr::setInetFamily(), cbee::Sockaddr::setIp(), and cbee::Sockaddr::setPort().
InetAddress() [2/3]
cbee::InetAddress::InetAddress (const char * ip, uint16_t port)
References address, cbee::Sockaddr::setInetFamily(), cbee::Sockaddr::setIp(), and cbee::Sockaddr::setPort().
InetAddress() [3/3]
cbee::InetAddress::InetAddress (const InetAddress &) private delete
Member Function Documentation
getIp()
std::string cbee::InetAddress::getIp () const
References address, and cbee::Sockaddr::getIp().
getIpPort()
std::string cbee::InetAddress::getIpPort () const
References address, cbee::Sockaddr::getIp(), and cbee::Sockaddr::getPort().
operator=()
InetAddress& cbee::InetAddress::operator= (const InetAddress &) private delete
Member Data Documentation
address
Sockaddr cbee::InetAddress::address private
Referenced by getIp(), getIpPort(), and InetAddress().
The documentation for this class was generated from the following files:
src/InetAddress.h
src/InetAddress.cpp