cbee: cbee::Sockaddr Class Reference
cbee::Sockaddr Class Reference
#include "Sockaddr.h"
Public Member Functions
Sockaddr ()
Sockaddr (uint16_t port, bool loopbackOnly=false)
Sockaddr (const char *ip, uint16_t port)
std::string getIp () const
std::string getIpPort () const
Private Member Functions
void setInetFamily ()
void setIp (const char *ip)
void setIp (bool loopbackOnly)
void setPort (uint16_t port)
Private Attributes
struct sockaddr_in address
Constructor & Destructor Documentation
Sockaddr() [1/3]
cbee::Sockaddr::Sockaddr ()
References address.
Sockaddr() [2/3]
cbee::Sockaddr::Sockaddr (uint16_t port, bool loopbackOnly = false)
References address, setInetFamily(), setIp(), and setPort().
Sockaddr() [3/3]
cbee::Sockaddr::Sockaddr (const char * ip, uint16_t port)
References address, setInetFamily(), setIp(), and setPort().
Member Function Documentation
getIp()
std::string cbee::Sockaddr::getIp () const
References address.
Referenced by getIpPort().
getIpPort()
std::string cbee::Sockaddr::getIpPort () const
References address, and getIp().
setInetFamily()
void cbee::Sockaddr::setInetFamily () private
References address.
Referenced by Sockaddr().
setIp() [1/2]
void cbee::Sockaddr::setIp (const char * ip) private
References address, and HANDLE_ERROR.
Referenced by Sockaddr().
setIp() [2/2]
void cbee::Sockaddr::setIp (bool loopbackOnly) private
References address.
setPort()
void cbee::Sockaddr::setPort (uint16_t port) private
References address.
Referenced by Sockaddr().
Member Data Documentation
address
struct sockaddr_in cbee::Sockaddr::address private
Referenced by getIp(), getIpPort(), setInetFamily(), setIp(), setPort(), and Sockaddr().
The documentation for this class was generated from the following files:
src/internal/system/Sockaddr.h
src/internal/system/Sockaddr.cpp