cbee: cbee::SocketFd Class Reference
cbee::SocketFd Class Reference
#include "SocketFd.h"
Public Member Functions
SocketFd ()
SocketFd (int socketFd)
~SocketFd ()
void shutdownRead () const
void shutdownWrite () const
void shutdown () const
void setNonBlock () const
void setReuseAddr () const
void bind (const Sockaddr &serverAddr) const
void listen () const
int accept (Sockaddr *connectAddr) const
void connect (const Sockaddr &serverAddr) const
int getFd () const
int read (void *buf, int count) const
int write (const void *buf, int count) const
Sockaddr getLocalAddr () const
Sockaddr getPeerAddr () const
Private Member Functions
SocketFd (const SocketFd &)=delete
SocketFd & operator= (const SocketFd &)=delete
struct sockaddr * sockaddrCast (Sockaddr *addr) const
const struct sockaddr * sockaddrCast (const Sockaddr *addr) const
Private Attributes
const int fd
Constructor & Destructor Documentation
SocketFd() [1/3]
cbee::SocketFd::SocketFd ()
References fd.
SocketFd() [2/3]
cbee::SocketFd::SocketFd (int socketFd) explicit
References fd.
~SocketFd()
cbee::SocketFd::~SocketFd ()
References fd.
SocketFd() [3/3]
cbee::SocketFd::SocketFd (const SocketFd &) private delete
Member Function Documentation
accept()
int cbee::SocketFd::accept (Sockaddr * connectAddr) const
References fd, HANDLE_ERROR, and sockaddrCast().
bind()
void cbee::SocketFd::bind (const Sockaddr & serverAddr) const
References fd, HANDLE_ERROR, and sockaddrCast().
connect()
void cbee::SocketFd::connect (const Sockaddr & serverAddr) const
References fd, HANDLE_ERROR, and sockaddrCast().
getFd()
int cbee::SocketFd::getFd () const
References fd.
getLocalAddr()
Sockaddr cbee::SocketFd::getLocalAddr () const
References fd, HANDLE_ERROR, and sockaddrCast().
getPeerAddr()
Sockaddr cbee::SocketFd::getPeerAddr () const
References fd, HANDLE_ERROR, and sockaddrCast().
listen()
void cbee::SocketFd::listen () const
References fd, and HANDLE_ERROR.
operator=()
SocketFd& cbee::SocketFd::operator= (const SocketFd &) private delete
read()
int cbee::SocketFd::read (void * buf, int count) const
References fd.
setNonBlock()
void cbee::SocketFd::setNonBlock () const
References fd, and HANDLE_ERROR.
setReuseAddr()
void cbee::SocketFd::setReuseAddr () const
References fd, and HANDLE_ERROR.
shutdown()
void cbee::SocketFd::shutdown () const
References fd, and HANDLE_ERROR.
Referenced by shutdownRead(), and shutdownWrite().
shutdownRead()
void cbee::SocketFd::shutdownRead () const
References fd, HANDLE_ERROR, and shutdown().
shutdownWrite()
void cbee::SocketFd::shutdownWrite () const
References fd, HANDLE_ERROR, and shutdown().
sockaddrCast() [1/2]
struct sockaddr * cbee::SocketFd::sockaddrCast (Sockaddr * addr) const private
Referenced by accept(), bind(), connect(), getLocalAddr(), and getPeerAddr().
sockaddrCast() [2/2]
const struct sockaddr * cbee::SocketFd::sockaddrCast (const Sockaddr * addr) const private
write()
int cbee::SocketFd::write (const void * buf, int count) const
References fd.
Member Data Documentation
fd
const int cbee::SocketFd::fd private
Referenced by accept(), bind(), connect(), getFd(), getLocalAddr(), getPeerAddr(), listen(), read(), setNonBlock(), setReuseAddr(), shutdown(), shutdownRead(), shutdownWrite(), SocketFd(), write(), and ~SocketFd().
The documentation for this class was generated from the following files:
src/internal/system/SocketFd.h
src/internal/system/SocketFd.cpp