cbee: cbee::IoManager Class Reference
cbee::IoManager Class Reference
#include "IoManager.h"
Public Types
typedef std::function< void()> Functor
Public Member Functions
IoManager ()
void loop ()
void quit ()
bool isInIoThread () const
void runInIoThread (Functor cb)
void updatePollerEvent (int fd, EventHandler event) const
void deletePollerEvent (int fd) const
int runAfter (double delay, TimerHandler::TimerFunc cb)
int runEvery (double interval, TimerHandler::TimerFunc cb)
void cancelTimerHandler (int handlerId)
Private Member Functions
IoManager (const IoManager &)=delete
IoManager & operator= (const IoManager &)=delete
void runPendingFunctors ()
Private Attributes
const std::thread::id ioThreadId
std::atomic< bool > quitFlag
EPoller poller
EventTrigger eventTrigger
EventTimerHandlerQueue timerHandlers
std::mutex mtx
std::vector< Functor > pendingFunctors
Member Typedef Documentation
Functor
typedef std::function<void()> cbee::IoManager::Functor
Constructor & Destructor Documentation
IoManager() [1/2]
cbee::IoManager::IoManager ()
IoManager() [2/2]
cbee::IoManager::IoManager (const IoManager &) private delete
Member Function Documentation
cancelTimerHandler()
void cbee::IoManager::cancelTimerHandler (int handlerId)
References cbee::EventTimerHandlerQueue::cancelHandler(), runInIoThread(), and timerHandlers.
deletePollerEvent()
void cbee::IoManager::deletePollerEvent (int fd) const
References cbee::EPoller::deleteEvent(), and poller.
Referenced by cbee::Acceptor::~Acceptor(), and cbee::Connection::~Connection().
isInIoThread()
bool cbee::IoManager::isInIoThread () const
References ioThreadId.
Referenced by cbee::Connection::handleRead(), cbee::Acceptor::handleRead(), loop(), and runInIoThread().
loop()
void cbee::IoManager::loop ()
References isInIoThread(), cbee::EPoller::poll(), poller, quitFlag, and runPendingFunctors().
operator=()
IoManager& cbee::IoManager::operator= (const IoManager &) private delete
quit()
void cbee::IoManager::quit ()
References eventTrigger, quitFlag, and cbee::EventTrigger::triggerOnce().
runAfter()
int cbee::IoManager::runAfter (double delay, TimerHandler::TimerFunc cb)
References cbee::EventTimerHandlerQueue::addHandler(), cbee::Timestamp::addSeconds(), cbee::TimerHandler::getId(), cbee::Timestamp::now(), runInIoThread(), and timerHandlers.
runEvery()
int cbee::IoManager::runEvery (double interval, TimerHandler::TimerFunc cb)
References cbee::EventTimerHandlerQueue::addHandler(), cbee::Timestamp::addSeconds(), cbee::TimerHandler::getId(), cbee::Timestamp::now(), runInIoThread(), and timerHandlers.
runInIoThread()
void cbee::IoManager::runInIoThread (Functor cb)
References eventTrigger, isInIoThread(), mtx, pendingFunctors, and cbee::EventTrigger::triggerOnce().
Referenced by cancelTimerHandler(), runAfter(), and runEvery().
runPendingFunctors()
void cbee::IoManager::runPendingFunctors () private
References mtx, and pendingFunctors.
Referenced by loop().
updatePollerEvent()
void cbee::IoManager::updatePollerEvent (int fd, EventHandler event) const
References poller, and cbee::EPoller::updateEvent().
Member Data Documentation
eventTrigger
EventTrigger cbee::IoManager::eventTrigger private
Referenced by quit(), and runInIoThread().
ioThreadId
const std::thread::id cbee::IoManager::ioThreadId private
Referenced by isInIoThread().
mtx
std::mutex cbee::IoManager::mtx private
Referenced by runInIoThread(), and runPendingFunctors().
pendingFunctors
std::vector<Functor> cbee::IoManager::pendingFunctors private
Referenced by runInIoThread(), and runPendingFunctors().
poller
EPoller cbee::IoManager::poller private
Referenced by deletePollerEvent(), loop(), and updatePollerEvent().
quitFlag
std::atomic<bool> cbee::IoManager::quitFlag private
Referenced by loop(), and quit().
timerHandlers
EventTimerHandlerQueue cbee::IoManager::timerHandlers private
Referenced by cancelTimerHandler(), runAfter(), and runEvery().
The documentation for this class was generated from the following files:
src/internal/IoManager.h
src/internal/IoManager.cpp