cbee: cbee::Timestamp Class Reference
cbee::Timestamp Class Reference
#include "Timestamp.h"
Public Member Functions
Timestamp ()
Timestamp (int64_t microSeconds)
int64_t getMicroSeconds () const
Timestamp addSeconds (double seconds) const
Static Public Member Functions
static Timestamp now ()
Static Public Attributes
static const int kMicroSecondsPerSecond = 1000 * 1000
Private Attributes
int64_t microSecondsSinceEpoch
Constructor & Destructor Documentation
Timestamp() [1/2]
cbee::Timestamp::Timestamp ()
Referenced by addSeconds(), and now().
Timestamp() [2/2]
cbee::Timestamp::Timestamp (int64_t microSeconds)
Member Function Documentation
addSeconds()
Timestamp cbee::Timestamp::addSeconds (double seconds) const
References kMicroSecondsPerSecond, microSecondsSinceEpoch, and Timestamp().
Referenced by cbee::TimerHandler::updateExpiredTime().
getMicroSeconds()
int64_t cbee::Timestamp::getMicroSeconds () const
References microSecondsSinceEpoch.
Referenced by cbee::EventTimerFd::getRelativeTimeFromNow(), cbee::operator!=(), cbee::operator<(), cbee::operator==(), and cbee::operator>().
now()
Timestamp cbee::Timestamp::now () static
References kMicroSecondsPerSecond, and Timestamp().
Referenced by cbee::EventTimerFd::getRelativeTimeFromNow().
Member Data Documentation
kMicroSecondsPerSecond
const int cbee::Timestamp::kMicroSecondsPerSecond = 1000 * 1000 static
Referenced by addSeconds(), cbee::EventTimerFd::getRelativeTimeFromNow(), and now().
microSecondsSinceEpoch
int64_t cbee::Timestamp::microSecondsSinceEpoch private
Referenced by addSeconds(), and getMicroSeconds().
The documentation for this class was generated from the following files:
src/internal/system/Timestamp.h
src/internal/system/Timestamp.cpp