cbee: cbee::Acceptor Class Reference
cbee::Acceptor Class Reference
#include "Acceptor.h"
Public Types
typedef std::function< void(int)> NewConnectionFunc
Public Member Functions
Acceptor (const IoManager &io, const NewConnectionFunc &newConn, const Sockaddr &listenAddr)
~Acceptor ()
Private Member Functions
void handleRead ()
Private Attributes
const IoManager & ioManager
const NewConnectionFunc newConnectionCallback
const SocketFd fd
Event event
Member Typedef Documentation
NewConnectionFunc
typedef std::function<void (int)> cbee::Acceptor::NewConnectionFunc
Constructor & Destructor Documentation
Acceptor()
cbee::Acceptor::Acceptor (const IoManager & io, const NewConnectionFunc & newConn, const Sockaddr & listenAddr)
~Acceptor()
cbee::Acceptor::~Acceptor ()
References cbee::IoManager::deletePollerEvent(), fd, cbee::SocketFd::getFd(), and ioManager.
Member Function Documentation
handleRead()
void cbee::Acceptor::handleRead () private
References cbee::SocketFd::accept(), fd, ioManager, cbee::IoManager::isInIoThread(), and newConnectionCallback.
Member Data Documentation
event
Event cbee::Acceptor::event private
fd
const SocketFd cbee::Acceptor::fd private
Referenced by handleRead(), and ~Acceptor().
ioManager
const IoManager& cbee::Acceptor::ioManager private
Referenced by handleRead(), and ~Acceptor().
newConnectionCallback
const NewConnectionFunc cbee::Acceptor::newConnectionCallback private
Referenced by handleRead().
The documentation for this class was generated from the following files:
src/internal/Acceptor.h
src/internal/Acceptor.cpp