cbee: cbee::EventTriggerFd Class Reference
cbee::EventTriggerFd Class Reference
#include "EventTriggerFd.h"
Public Member Functions
EventTriggerFd ()
~EventTriggerFd ()
int cleanEvents () const
void triggerEvent () const
int getFd () const
Private Member Functions
EventTriggerFd (const EventTriggerFd &)=delete
EventTriggerFd & operator= (const EventTriggerFd &)=delete
Private Attributes
const int fd
Constructor & Destructor Documentation
EventTriggerFd() [1/2]
cbee::EventTriggerFd::EventTriggerFd ()
References fd.
~EventTriggerFd()
cbee::EventTriggerFd::~EventTriggerFd ()
References fd.
EventTriggerFd() [2/2]
cbee::EventTriggerFd::EventTriggerFd (const EventTriggerFd &) private delete
Member Function Documentation
cleanEvents()
int cbee::EventTriggerFd::cleanEvents () const
References fd, and HANDLE_ERROR.
Referenced by cbee::EventTrigger::handleRead().
getFd()
int cbee::EventTriggerFd::getFd () const
References fd.
Referenced by cbee::EventTrigger::EventTrigger(), and cbee::EventTrigger::~EventTrigger().
operator=()
EventTriggerFd& cbee::EventTriggerFd::operator= (const EventTriggerFd &) private delete
triggerEvent()
void cbee::EventTriggerFd::triggerEvent () const
References fd, and HANDLE_ERROR.
Referenced by cbee::EventTrigger::triggerOnce().
Member Data Documentation
fd
const int cbee::EventTriggerFd::fd private
Referenced by cleanEvents(), EventTriggerFd(), getFd(), triggerEvent(), and ~EventTriggerFd().
The documentation for this class was generated from the following files:
src/internal/system/EventTriggerFd.h
src/internal/system/EventTriggerFd.cpp