cbee: cbee::EventTimerFd Class Reference
cbee::EventTimerFd Class Reference
#include "EventTimerFd.h"
Public Member Functions
EventTimerFd ()
~EventTimerFd ()
void cleanEvent ()
void resetEventTimer (Timestamp expiredTime)
int getFd () const
Private Member Functions
struct timespec getRelativeTimeFromNow (Timestamp expiredTime) const
Private Attributes
const int fd
Constructor & Destructor Documentation
EventTimerFd()
cbee::EventTimerFd::EventTimerFd ()
References fd.
~EventTimerFd()
cbee::EventTimerFd::~EventTimerFd ()
References fd.
Member Function Documentation
cleanEvent()
void cbee::EventTimerFd::cleanEvent ()
References fd, and HANDLE_ERROR.
getFd()
int cbee::EventTimerFd::getFd () const
References fd.
getRelativeTimeFromNow()
struct timespec cbee::EventTimerFd::getRelativeTimeFromNow (Timestamp expiredTime) const private
References cbee::Timestamp::getMicroSeconds(), cbee::Timestamp::kMicroSecondsPerSecond, and cbee::Timestamp::now().
Referenced by resetEventTimer().
resetEventTimer()
void cbee::EventTimerFd::resetEventTimer (Timestamp expiredTime)
References fd, getRelativeTimeFromNow(), and HANDLE_ERROR.
Member Data Documentation
fd
const int cbee::EventTimerFd::fd private
Referenced by cleanEvent(), EventTimerFd(), getFd(), resetEventTimer(), and ~EventTimerFd().
The documentation for this class was generated from the following files:
src/internal/system/EventTimerFd.h
src/internal/system/EventTimerFd.cpp