cbee: el::LogDispatchCallback Class Reference
el::LogDispatchCallback Class Reference
#include "easylogging++.h"
Protected Member Functions
virtual void handle (const LogDispatchData *data)
base::threading::Mutex & fileHandle (const LogDispatchData *data)
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Attributes
std::unordered_map< std::string, std::unique_ptr< base::threading::Mutex > > m_fileLocks
base::threading::Mutex m_fileLocksMapLock
Friends
class base::LogDispatcher
Additional Inherited Members
Public Member Functions inherited from el::Callback< LogDispatchData >
Callback (void)
bool enabled (void) const
void setEnabled (bool enabled)
Member Function Documentation
fileHandle()
base::threading::Mutex & el::LogDispatchCallback::fileHandle (const LogDispatchData * data) protected
References el::base::TypedConfigurations::filename(), el::LogMessage::level(), el::LogMessage::logger(), el::LogDispatchData::logMessage(), and el::Logger::typedConfigurations().
handle()
void el::LogDispatchCallback::handle (const LogDispatchData * data) protected virtual
Implements el::Callback< LogDispatchData >.
Reimplemented in el::base::DefaultLogDispatchCallback.
References el::base::TypedConfigurations::filename(), el::LogMessage::level(), el::base::threading::ThreadSafe::lock(), el::LogMessage::logger(), el::LogDispatchData::logMessage(), and el::Logger::typedConfigurations().
Referenced by el::base::LogDispatcher::dispatch(), and el::base::DefaultLogDispatchCallback::handle().
Friends And Related Function Documentation
base::LogDispatcher
friend class base::LogDispatcher friend
Member Data Documentation
m_fileLocks
std::unordered_map<std::string, std::unique_ptr<base::threading::Mutex> > el::LogDispatchCallback::m_fileLocks private
m_fileLocksMapLock
base::threading::Mutex el::LogDispatchCallback::m_fileLocksMapLock private
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp