cbee: cbee::Logger Class Reference
cbee::Logger Class Reference
#include "Logger.h"
Static Public Member Functions
static void config ()
Member Function Documentation
config()
void cbee::Logger::config () static
References el::Error, el::Fatal, el::Filename, el::Format, el::Loggers::reconfigureLogger(), el::Configurations::set(), el::Configurations::setGlobally(), and el::Configurations::setToDefault().
Referenced by cbee::Initializer::Initializer().
The documentation for this class was generated from the following files:
src/log/Logger.h
src/log/Logger.cpp