cbee: cbee::EPoller Class Reference
cbee::EPoller Class Reference
#include "EPoller.h"
Public Member Functions
EPoller ()
~EPoller ()
void updateSocketEvent (const Socket &socket, SocketEventHandler event) const
void deleteSocketEvent (const Socket &socket) const
std::vector< SocketEventHandler > poll (int timeoutMs)
Private Member Functions
EPoller (const EPoller &)=delete
EPoller & operator= (const EPoller &)=delete
Private Attributes
int epollFd
std::vector< struct epoll_event > pollContainer
Constructor & Destructor Documentation
EPoller() [1/2]
cbee::EPoller::EPoller ()
References epollFd.
~EPoller()
cbee::EPoller::~EPoller ()
References epollFd.
EPoller() [2/2]
cbee::EPoller::EPoller (const EPoller &) private delete
Member Function Documentation
deleteSocketEvent()
void cbee::EPoller::deleteSocketEvent (const Socket & socket) const
References epollFd, and cbee::Socket::getFd().
operator=()
EPoller& cbee::EPoller::operator= (const EPoller &) private delete
poll()
std::vector< SocketEventHandler > cbee::EPoller::poll (int timeoutMs)
References epollFd, cbee::i, pollContainer, and cbee::SocketEvent::setActiveEvents().
updateSocketEvent()
void cbee::EPoller::updateSocketEvent (const Socket & socket, SocketEventHandler event) const
References epollFd, and cbee::Socket::getFd().
Member Data Documentation
epollFd
int cbee::EPoller::epollFd private
Referenced by deleteSocketEvent(), EPoller(), poll(), updateSocketEvent(), and ~EPoller().
pollContainer
std::vector<struct epoll_event> cbee::EPoller::pollContainer private
Referenced by poll().
The documentation for this class was generated from the following files:
src/internal/system/EPoller.h
src/internal/system/EPoller.cpp