cbee: el::base::DefaultLogBuilder Class Reference
el::base::DefaultLogBuilder Class Reference
#include "easylogging++.h"
Public Member Functions
base::type::string_t build (const LogMessage *logMessage, bool appendNewLine) const
Public Member Functions inherited from el::LogBuilder
LogBuilder ()
virtual ~LogBuilder (void)
void convertToColoredOutput (base::type::string_t *logLine, Level level)
Member Function Documentation
build()
base::type::string_t el::base::DefaultLogBuilder::build (const LogMessage * logMessage, bool appendNewLine) const virtual
Implements el::LogBuilder.
References el::base::utils::Str::addToBuff(), el::base::AppName, el::base::utils::File::buildBaseFilename(), el::base::utils::File::buildStrippedFilename(), el::base::utils::Str::clearBuff(), el::base::utils::Str::convertAndAddToBuff(), el::base::DateTime, el::base::LogFormat::dateTimeFormat(), ELPP, ELPP_LITERAL, ELPP_UNUSED, el::base::File, el::LogMessage::file(), el::base::FileBase, el::base::LogFormat::format(), el::LogMessage::func(), el::base::Function, el::base::threading::getCurrentThreadId(), el::base::utils::DateTime::getDateTime(), el::base::LogFormat::hasFlag(), el::base::consts::kAppNameFormatSpecifier, el::base::consts::kDateTimeFormatSpecifier, el::base::consts::kLogFileBaseFormatSpecifier, el::base::consts::kLogFileFormatSpecifier, el::base::consts::kLogFunctionFormatSpecifier, el::base::consts::kLogLineFormatSpecifier, el::base::consts::kLogLocationFormatSpecifier, el::base::consts::kMessageFormatSpecifier, el::base::consts::kSourceFilenameMaxLength, el::base::consts::kSourceLineMaxLength, el::base::consts::kThreadIdFormatSpecifier, el::base::consts::kVerboseLevelFormatSpecifier, el::LogMessage::level(), el::base::Line, el::LogMessage::line(), el::base::Location, el::base::TypedConfigurations::logFormat(), el::LogMessage::logger(), el::base::LogMessage, el::LogMessage::message(), el::Logger::parentApplicationName(), el::base::utils::Str::replaceFirstWithEscape(), el::base::TypedConfigurations::subsecondPrecision(), el::base::ThreadId, el::Logger::typedConfigurations(), el::Verbose, el::base::VerboseLevel, and el::LogMessage::verboseLevel().
The documentation for this class was generated from the following files:
src/internal/lib/easylogging++.h
src/internal/lib/easylogging++.cpp