cbee: cbee::Connection Class Reference
cbee::Connection Class Reference
#include "Connection.h"
Public Member Functions
Connection (const IoManager &io, const int connFd, Event::RemoveFunc removeCallback)
~Connection ()
Private Member Functions
Connection (const Connection &)=delete
Connection & operator= (const Connection &)=delete
void handleRead ()
void handleWrite ()
void handleError ()
Private Attributes
const IoManager & ioManager
const SocketFd fd
Event event
Constructor & Destructor Documentation
Connection() [1/2]
cbee::Connection::Connection (const IoManager & io, const int connFd, Event::RemoveFunc removeCallback)
~Connection()
cbee::Connection::~Connection ()
References cbee::IoManager::deletePollerEvent(), fd, cbee::SocketFd::getFd(), and ioManager.
Connection() [2/2]
cbee::Connection::Connection (const Connection &) private delete
Member Function Documentation
handleError()
void cbee::Connection::handleError () private
handleRead()
void cbee::Connection::handleRead () private
References ioManager, and cbee::IoManager::isInIoThread().
handleWrite()
void cbee::Connection::handleWrite () private
operator=()
Connection& cbee::Connection::operator= (const Connection &) private delete
Member Data Documentation
event
Event cbee::Connection::event private
fd
const SocketFd cbee::Connection::fd private
Referenced by ~Connection().
ioManager
const IoManager& cbee::Connection::ioManager private
Referenced by handleRead(), and ~Connection().
The documentation for this class was generated from the following files:
src/internal/Connection.h
src/internal/Connection.cpp